package jp.co.fois.sales.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;


/**
 * <pre>
 * 会社条件テーブル.
 * 
 * 【変更履歴】
 * 1.00 2019/12/02 新規作成
 * </pre>
 * 
 * @author T.Yagi
 * @version 1.00
 */
public class CompanyExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public CompanyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        /** 条件リスト. */
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaIsNull() {
            addCriterion("COMPANY_NAME_KANA is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaIsNotNull() {
            addCriterion("COMPANY_NAME_KANA is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaEqualTo(String value) {
            addCriterion("COMPANY_NAME_KANA =", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaNotEqualTo(String value) {
            addCriterion("COMPANY_NAME_KANA <>", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaGreaterThan(String value) {
            addCriterion("COMPANY_NAME_KANA >", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME_KANA >=", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaLessThan(String value) {
            addCriterion("COMPANY_NAME_KANA <", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME_KANA <=", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaLike(String value) {
            addCriterion("COMPANY_NAME_KANA like", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaNotLike(String value) {
            addCriterion("COMPANY_NAME_KANA not like", value, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaIn(List<String> values) {
            addCriterion("COMPANY_NAME_KANA in", values, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaNotIn(List<String> values) {
            addCriterion("COMPANY_NAME_KANA not in", values, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME_KANA between", value1, value2, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andCompanyNameKanaNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME_KANA not between", value1, value2, "CompanyNameKana");
            return (Criteria) this;
        }

        public Criteria andHpIsNull() {
            addCriterion("HP is null");
            return (Criteria) this;
        }

        public Criteria andHpIsNotNull() {
            addCriterion("HP is not null");
            return (Criteria) this;
        }

        public Criteria andHpEqualTo(String value) {
            addCriterion("HP =", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotEqualTo(String value) {
            addCriterion("HP <>", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpGreaterThan(String value) {
            addCriterion("HP >", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpGreaterThanOrEqualTo(String value) {
            addCriterion("HP >=", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpLessThan(String value) {
            addCriterion("HP <", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpLessThanOrEqualTo(String value) {
            addCriterion("HP <=", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpLike(String value) {
            addCriterion("HP like", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotLike(String value) {
            addCriterion("HP not like", value, "hp");
            return (Criteria) this;
        }

        public Criteria andHpIn(List<String> values) {
            addCriterion("HP in", values, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotIn(List<String> values) {
            addCriterion("HP not in", values, "hp");
            return (Criteria) this;
        }

        public Criteria andHpBetween(String value1, String value2) {
            addCriterion("HP between", value1, value2, "hp");
            return (Criteria) this;
        }

        public Criteria andHpNotBetween(String value1, String value2) {
            addCriterion("HP not between", value1, value2, "hp");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberIsNull() {
            addCriterion("EMPLOYEE_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberIsNotNull() {
            addCriterion("EMPLOYEE_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberEqualTo(Integer value) {
            addCriterion("EMPLOYEE_NUMBER =", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberNotEqualTo(Integer value) {
            addCriterion("EMPLOYEE_NUMBER <>", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberGreaterThan(Integer value) {
            addCriterion("EMPLOYEE_NUMBER >", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("EMPLOYEE_NUMBER >=", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberLessThan(Integer value) {
            addCriterion("EMPLOYEE_NUMBER <", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberLessThanOrEqualTo(Integer value) {
            addCriterion("EMPLOYEE_NUMBER <=", value, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberIn(List<Integer> values) {
            addCriterion("EMPLOYEE_NUMBER in", values, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberNotIn(List<Integer> values) {
            addCriterion("EMPLOYEE_NUMBER not in", values, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberBetween(Integer value1, Integer value2) {
            addCriterion("EMPLOYEE_NUMBER between", value1, value2, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andEmployeeNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("EMPLOYEE_NUMBER not between", value1, value2, "employeeNumber");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNull() {
            addCriterion("COMPANY_TEL is null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIsNotNull() {
            addCriterion("COMPANY_TEL is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyTelEqualTo(String value) {
            addCriterion("COMPANY_TEL =", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotEqualTo(String value) {
            addCriterion("COMPANY_TEL <>", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThan(String value) {
            addCriterion("COMPANY_TEL >", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_TEL >=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThan(String value) {
            addCriterion("COMPANY_TEL <", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_TEL <=", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelLike(String value) {
            addCriterion("COMPANY_TEL like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotLike(String value) {
            addCriterion("COMPANY_TEL not like", value, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelIn(List<String> values) {
            addCriterion("COMPANY_TEL in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotIn(List<String> values) {
            addCriterion("COMPANY_TEL not in", values, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelBetween(String value1, String value2) {
            addCriterion("COMPANY_TEL between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCompanyTelNotBetween(String value1, String value2) {
            addCriterion("COMPANY_TEL not between", value1, value2, "companyTel");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNull() {
            addCriterion("CAPITAL is null");
            return (Criteria) this;
        }

        public Criteria andCapitalIsNotNull() {
            addCriterion("CAPITAL is not null");
            return (Criteria) this;
        }

        public Criteria andCapitalEqualTo(Integer value) {
            addCriterion("CAPITAL =", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotEqualTo(Integer value) {
            addCriterion("CAPITAL <>", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThan(Integer value) {
            addCriterion("CAPITAL >", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalGreaterThanOrEqualTo(Integer value) {
            addCriterion("CAPITAL >=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThan(Integer value) {
            addCriterion("CAPITAL <", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalLessThanOrEqualTo(Integer value) {
            addCriterion("CAPITAL <=", value, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalIn(List<Integer> values) {
            addCriterion("CAPITAL in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotIn(List<Integer> values) {
            addCriterion("CAPITAL not in", values, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalBetween(Integer value1, Integer value2) {
            addCriterion("CAPITAL between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andCapitalNotBetween(Integer value1, Integer value2) {
            addCriterion("CAPITAL not between", value1, value2, "capital");
            return (Criteria) this;
        }

        public Criteria andFoundationIsNull() {
            addCriterion("FOUNDATION is null");
            return (Criteria) this;
        }

        public Criteria andFoundationIsNotNull() {
            addCriterion("FOUNDATION is not null");
            return (Criteria) this;
        }

        public Criteria andFoundationEqualTo(Date value) {
            addCriterionForJDBCDate("FOUNDATION =", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationNotEqualTo(Date value) {
            addCriterionForJDBCDate("FOUNDATION <>", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationGreaterThan(Date value) {
            addCriterionForJDBCDate("FOUNDATION >", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FOUNDATION >=", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationLessThan(Date value) {
            addCriterionForJDBCDate("FOUNDATION <", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("FOUNDATION <=", value, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationIn(List<Date> values) {
            addCriterionForJDBCDate("FOUNDATION in", values, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationNotIn(List<Date> values) {
            addCriterionForJDBCDate("FOUNDATION not in", values, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FOUNDATION between", value1, value2, "foundation");
            return (Criteria) this;
        }

        public Criteria andFoundationNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("FOUNDATION not between", value1, value2, "foundation");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsIsNull() {
            addCriterion("BUSINESS_CONTENTS is null");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsIsNotNull() {
            addCriterion("BUSINESS_CONTENTS is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsEqualTo(String value) {
            addCriterion("BUSINESS_CONTENTS =", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsNotEqualTo(String value) {
            addCriterion("BUSINESS_CONTENTS <>", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsGreaterThan(String value) {
            addCriterion("BUSINESS_CONTENTS >", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_CONTENTS >=", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsLessThan(String value) {
            addCriterion("BUSINESS_CONTENTS <", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_CONTENTS <=", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsLike(String value) {
            addCriterion("BUSINESS_CONTENTS like", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsNotLike(String value) {
            addCriterion("BUSINESS_CONTENTS not like", value, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsIn(List<String> values) {
            addCriterion("BUSINESS_CONTENTS in", values, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsNotIn(List<String> values) {
            addCriterion("BUSINESS_CONTENTS not in", values, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsBetween(String value1, String value2) {
            addCriterion("BUSINESS_CONTENTS between", value1, value2, "businessContents");
            return (Criteria) this;
        }

        public Criteria andBusinessContentsNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_CONTENTS not between", value1, value2, "businessContents");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("rank is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("rank is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(String value) {
            addCriterion("rank =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(String value) {
            addCriterion("rank <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(String value) {
            addCriterion("rank >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(String value) {
            addCriterion("rank >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(String value) {
            addCriterion("rank <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(String value) {
            addCriterion("rank <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLike(String value) {
            addCriterion("rank like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotLike(String value) {
            addCriterion("rank not like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<String> values) {
            addCriterion("rank in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<String> values) {
            addCriterion("rank not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(String value1, String value2) {
            addCriterion("rank between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(String value1, String value2) {
            addCriterion("rank not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIsNull() {
            addCriterion("TRADING_ACHIEVEMENT is null");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIsNotNull() {
            addCriterion("TRADING_ACHIEVEMENT is not null");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT =", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <>", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementGreaterThan(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT >", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementGreaterThanOrEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT >=", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementLessThan(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementLessThanOrEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <=", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIn(List<Boolean> values) {
            addCriterion("TRADING_ACHIEVEMENT in", values, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotIn(List<Boolean> values) {
            addCriterion("TRADING_ACHIEVEMENT not in", values, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementBetween(Boolean value1, Boolean value2) {
            addCriterion("TRADING_ACHIEVEMENT between", value1, value2, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotBetween(Boolean value1, Boolean value2) {
            addCriterion("TRADING_ACHIEVEMENT not between", value1, value2, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.COMPANY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criterion {
        /** Where句. */
        private String condition;

        /** Where句(値). */
        private Object value;

        /** LIKE検索の場合の後方値. */
        private Object secondValue;

        /** 値が設定されているか. */
        private boolean noValue;

        /** 完全一致フラグ. */
        private boolean singleValue;

        /** 前方一致フラグ. */
        private boolean betweenValue;

        /** List保持. */
        private boolean listValue;

        /** タイプハンドラ. */
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
