package jp.co.fois.sales.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <pre>
 * CSV出力条件クラス.
 * 
 * 【変更履歴】
 * 1.00 2019/12/02 新規作成
 * </pre>
 * 
 * @author T.Yagi
 * @version 1.00
 */
public class CsvOutputResultExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public CsvOutputResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        /** 条件リスト. */
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCsvOutputIdIsNull() {
            addCriterion("CSV_OUTPUT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdIsNotNull() {
            addCriterion("CSV_OUTPUT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdEqualTo(String value) {
            addCriterion("CSV_OUTPUT_ID =", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdNotEqualTo(String value) {
            addCriterion("CSV_OUTPUT_ID <>", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdGreaterThan(String value) {
            addCriterion("CSV_OUTPUT_ID >", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdGreaterThanOrEqualTo(String value) {
            addCriterion("CSV_OUTPUT_ID >=", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdLessThan(String value) {
            addCriterion("CSV_OUTPUT_ID <", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdLessThanOrEqualTo(String value) {
            addCriterion("CSV_OUTPUT_ID <=", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdLike(String value) {
            addCriterion("CSV_OUTPUT_ID like", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdNotLike(String value) {
            addCriterion("CSV_OUTPUT_ID not like", value, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdIn(List<String> values) {
            addCriterion("CSV_OUTPUT_ID in", values, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdNotIn(List<String> values) {
            addCriterion("CSV_OUTPUT_ID not in", values, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdBetween(String value1, String value2) {
            addCriterion("CSV_OUTPUT_ID between", value1, value2, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andCsvOutputIdNotBetween(String value1, String value2) {
            addCriterion("CSV_OUTPUT_ID not between", value1, value2, "csvOutputId");
            return (Criteria) this;
        }

        public Criteria andOutputDateIsNull() {
            addCriterion("OUTPUT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andOutputDateIsNotNull() {
            addCriterion("OUTPUT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andOutputDateEqualTo(Date value) {
            addCriterion("OUTPUT_DATE =", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateNotEqualTo(Date value) {
            addCriterion("OUTPUT_DATE <>", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateGreaterThan(Date value) {
            addCriterion("OUTPUT_DATE >", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateGreaterThanOrEqualTo(Date value) {
            addCriterion("OUTPUT_DATE >=", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateLessThan(Date value) {
            addCriterion("OUTPUT_DATE <", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateLessThanOrEqualTo(Date value) {
            addCriterion("OUTPUT_DATE <=", value, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateIn(List<Date> values) {
            addCriterion("OUTPUT_DATE in", values, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateNotIn(List<Date> values) {
            addCriterion("OUTPUT_DATE not in", values, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateBetween(Date value1, Date value2) {
            addCriterion("OUTPUT_DATE between", value1, value2, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputDateNotBetween(Date value1, Date value2) {
            addCriterion("OUTPUT_DATE not between", value1, value2, "outputDate");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountIsNull() {
            addCriterion("OUTPUT_ROW_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountIsNotNull() {
            addCriterion("OUTPUT_ROW_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountEqualTo(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT =", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountNotEqualTo(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT <>", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountGreaterThan(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT >", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT >=", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountLessThan(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT <", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountLessThanOrEqualTo(Integer value) {
            addCriterion("OUTPUT_ROW_COUNT <=", value, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountIn(List<Integer> values) {
            addCriterion("OUTPUT_ROW_COUNT in", values, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountNotIn(List<Integer> values) {
            addCriterion("OUTPUT_ROW_COUNT not in", values, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountBetween(Integer value1, Integer value2) {
            addCriterion("OUTPUT_ROW_COUNT between", value1, value2, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andOutputRowCountNotBetween(Integer value1, Integer value2) {
            addCriterion("OUTPUT_ROW_COUNT not between", value1, value2, "outputRowCount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.CSV_OUTPUT_RESULT
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criterion {
        /** Where句. */
        private String condition;

        /** Where句(値). */
        private Object value;

        /** LIKE検索の場合の後方値. */
        private Object secondValue;

        /** 値が設定されているか. */
        private boolean noValue;

        /** 完全一致フラグ. */
        private boolean singleValue;

        /** 前方一致フラグ. */
        private boolean betweenValue;

        /** List保持. */
        private boolean listValue;

        /** タイプハンドラ. */
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
