package jp.co.fois.sales.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;


/**
 * <pre>
 * 営業活動条件クラス.
 * 
 * 【変更履歴】
 * 1.00 2019/12/02 新規作成
 * </pre>
 * 
 * @author T.Yagi
 * @version 1.00
 */
public class SalesActivityExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public SalesActivityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    protected abstract static class GeneratedCriteria {
        /** 条件リスト. */
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("COMPANY_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("COMPANY_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("COMPANY_NAME =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("COMPANY_NAME <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("COMPANY_NAME >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("COMPANY_NAME <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("COMPANY_NAME <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("COMPANY_NAME like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("COMPANY_NAME not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("COMPANY_NAME in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("COMPANY_NAME not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("COMPANY_NAME not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleIsNull() {
            addCriterion("SALES_WORK_RESPONSIBLE is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleIsNotNull() {
            addCriterion("SALES_WORK_RESPONSIBLE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleEqualTo(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE =", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleNotEqualTo(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE <>", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleGreaterThan(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE >", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE >=", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleLessThan(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE <", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleLessThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE <=", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleLike(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE like", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleNotLike(String value) {
            addCriterion("SALES_WORK_RESPONSIBLE not like", value, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleIn(List<String> values) {
            addCriterion("SALES_WORK_RESPONSIBLE in", values, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleNotIn(List<String> values) {
            addCriterion("SALES_WORK_RESPONSIBLE not in", values, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleBetween(String value1, String value2) {
            addCriterion("SALES_WORK_RESPONSIBLE between", value1, value2, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkResponsibleNotBetween(String value1, String value2) {
            addCriterion("SALES_WORK_RESPONSIBLE not between", value1, value2, "salesWorkResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayIsNull() {
            addCriterion("SALES_WORK_BUSINESS_DAY is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayIsNotNull() {
            addCriterion("SALES_WORK_BUSINESS_DAY is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY =", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayNotEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY <>", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayGreaterThan(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY >", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY >=", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayLessThan(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY <", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY <=", value, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayIn(List<Date> values) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY in", values, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayNotIn(List<Date> values) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY not in", values, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY between", value1, value2, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBusinessDayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALES_WORK_BUSINESS_DAY not between", value1, value2, "salesWorkBusinessDay");
            return (Criteria) this;
        }

        public Criteria andRankIsNull() {
            addCriterion("RANK is null");
            return (Criteria) this;
        }

        public Criteria andRankIsNotNull() {
            addCriterion("RANK is not null");
            return (Criteria) this;
        }

        public Criteria andRankEqualTo(String value) {
            addCriterion("RANK =", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotEqualTo(String value) {
            addCriterion("RANK <>", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThan(String value) {
            addCriterion("RANK >", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankGreaterThanOrEqualTo(String value) {
            addCriterion("RANK >=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThan(String value) {
            addCriterion("RANK <", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLessThanOrEqualTo(String value) {
            addCriterion("RANK <=", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankLike(String value) {
            addCriterion("RANK like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotLike(String value) {
            addCriterion("RANK not like", value, "rank");
            return (Criteria) this;
        }

        public Criteria andRankIn(List<String> values) {
            addCriterion("RANK in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotIn(List<String> values) {
            addCriterion("RANK not in", values, "rank");
            return (Criteria) this;
        }

        public Criteria andRankBetween(String value1, String value2) {
            addCriterion("RANK between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andRankNotBetween(String value1, String value2) {
            addCriterion("RANK not between", value1, value2, "rank");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIsNull() {
            addCriterion("TRADING_ACHIEVEMENT is null");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIsNotNull() {
            addCriterion("TRADING_ACHIEVEMENT is not null");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT =", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <>", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementGreaterThan(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT >", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementGreaterThanOrEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT >=", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementLessThan(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementLessThanOrEqualTo(Boolean value) {
            addCriterion("TRADING_ACHIEVEMENT <=", value, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementIn(List<Boolean> values) {
            addCriterion("TRADING_ACHIEVEMENT in", values, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotIn(List<Boolean> values) {
            addCriterion("TRADING_ACHIEVEMENT not in", values, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementBetween(Boolean value1, Boolean value2) {
            addCriterion("TRADING_ACHIEVEMENT between", value1, value2, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andTradingAchievementNotBetween(Boolean value1, Boolean value2) {
            addCriterion("TRADING_ACHIEVEMENT not between", value1, value2, "tradingAchievement");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseIsNull() {
            addCriterion("SALES_WORK_BASE is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseIsNotNull() {
            addCriterion("SALES_WORK_BASE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseEqualTo(String value) {
            addCriterion("SALES_WORK_BASE =", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseNotEqualTo(String value) {
            addCriterion("SALES_WORK_BASE <>", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseGreaterThan(String value) {
            addCriterion("SALES_WORK_BASE >", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_BASE >=", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseLessThan(String value) {
            addCriterion("SALES_WORK_BASE <", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseLessThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_BASE <=", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseLike(String value) {
            addCriterion("SALES_WORK_BASE like", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseNotLike(String value) {
            addCriterion("SALES_WORK_BASE not like", value, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseIn(List<String> values) {
            addCriterion("SALES_WORK_BASE in", values, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseNotIn(List<String> values) {
            addCriterion("SALES_WORK_BASE not in", values, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseBetween(String value1, String value2) {
            addCriterion("SALES_WORK_BASE between", value1, value2, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkBaseNotBetween(String value1, String value2) {
            addCriterion("SALES_WORK_BASE not between", value1, value2, "salesWorkBase");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunIsNull() {
            addCriterion("SALES_WORK_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunIsNotNull() {
            addCriterion("SALES_WORK_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunEqualTo(String value) {
            addCriterion("SALES_WORK_KUBUN =", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunNotEqualTo(String value) {
            addCriterion("SALES_WORK_KUBUN <>", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunGreaterThan(String value) {
            addCriterion("SALES_WORK_KUBUN >", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_KUBUN >=", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunLessThan(String value) {
            addCriterion("SALES_WORK_KUBUN <", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunLessThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_KUBUN <=", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunLike(String value) {
            addCriterion("SALES_WORK_KUBUN like", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunNotLike(String value) {
            addCriterion("SALES_WORK_KUBUN not like", value, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunIn(List<String> values) {
            addCriterion("SALES_WORK_KUBUN in", values, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunNotIn(List<String> values) {
            addCriterion("SALES_WORK_KUBUN not in", values, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunBetween(String value1, String value2) {
            addCriterion("SALES_WORK_KUBUN between", value1, value2, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkKubunNotBetween(String value1, String value2) {
            addCriterion("SALES_WORK_KUBUN not between", value1, value2, "salesWorkKubun");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleIsNull() {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleIsNotNull() {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleEqualTo(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE =", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleNotEqualTo(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE <>", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleGreaterThan(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE >", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE >=", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleLessThan(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE <", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleLessThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE <=", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleLike(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE like", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleNotLike(String value) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE not like", value, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleIn(List<String> values) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE in", values, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleNotIn(List<String> values) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE not in", values, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleBetween(String value1, String value2) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE between", value1, value2, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkCustomerResponsibleNotBetween(String value1, String value2) {
            addCriterion("SALES_WORK_CUSTOMER_RESPONSIBLE not between", value1, value2, "salesWorkCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailIsNull() {
            addCriterion("SALES_WORK_WORK_DETAIL is null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailIsNotNull() {
            addCriterion("SALES_WORK_WORK_DETAIL is not null");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailEqualTo(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL =", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailNotEqualTo(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL <>", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailGreaterThan(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL >", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL >=", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailLessThan(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL <", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailLessThanOrEqualTo(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL <=", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailLike(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL like", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailNotLike(String value) {
            addCriterion("SALES_WORK_WORK_DETAIL not like", value, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailIn(List<String> values) {
            addCriterion("SALES_WORK_WORK_DETAIL in", values, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailNotIn(List<String> values) {
            addCriterion("SALES_WORK_WORK_DETAIL not in", values, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailBetween(String value1, String value2) {
            addCriterion("SALES_WORK_WORK_DETAIL between", value1, value2, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesWorkWorkDetailNotBetween(String value1, String value2) {
            addCriterion("SALES_WORK_WORK_DETAIL not between", value1, value2, "salesWorkWorkDetail");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseIsNull() {
            addCriterion("SALES_PLAN_BASE is null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseIsNotNull() {
            addCriterion("SALES_PLAN_BASE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseEqualTo(String value) {
            addCriterion("SALES_PLAN_BASE =", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseNotEqualTo(String value) {
            addCriterion("SALES_PLAN_BASE <>", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseGreaterThan(String value) {
            addCriterion("SALES_PLAN_BASE >", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_BASE >=", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseLessThan(String value) {
            addCriterion("SALES_PLAN_BASE <", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseLessThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_BASE <=", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseLike(String value) {
            addCriterion("SALES_PLAN_BASE like", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseNotLike(String value) {
            addCriterion("SALES_PLAN_BASE not like", value, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseIn(List<String> values) {
            addCriterion("SALES_PLAN_BASE in", values, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseNotIn(List<String> values) {
            addCriterion("SALES_PLAN_BASE not in", values, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_BASE between", value1, value2, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanBaseNotBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_BASE not between", value1, value2, "salesPlanBase");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleIsNull() {
            addCriterion("SALES_PLAN_RESPONSIBLE is null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleIsNotNull() {
            addCriterion("SALES_PLAN_RESPONSIBLE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleEqualTo(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE =", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleNotEqualTo(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE <>", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleGreaterThan(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE >", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE >=", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleLessThan(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE <", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleLessThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE <=", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleLike(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE like", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleNotLike(String value) {
            addCriterion("SALES_PLAN_RESPONSIBLE not like", value, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleIn(List<String> values) {
            addCriterion("SALES_PLAN_RESPONSIBLE in", values, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleNotIn(List<String> values) {
            addCriterion("SALES_PLAN_RESPONSIBLE not in", values, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_RESPONSIBLE between", value1, value2, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanResponsibleNotBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_RESPONSIBLE not between", value1, value2, "salesPlanResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunIsNull() {
            addCriterion("SALES_PLAN_KUBUN is null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunIsNotNull() {
            addCriterion("SALES_PLAN_KUBUN is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunEqualTo(String value) {
            addCriterion("SALES_PLAN_KUBUN =", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunNotEqualTo(String value) {
            addCriterion("SALES_PLAN_KUBUN <>", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunGreaterThan(String value) {
            addCriterion("SALES_PLAN_KUBUN >", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_KUBUN >=", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunLessThan(String value) {
            addCriterion("SALES_PLAN_KUBUN <", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunLessThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_KUBUN <=", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunLike(String value) {
            addCriterion("SALES_PLAN_KUBUN like", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunNotLike(String value) {
            addCriterion("SALES_PLAN_KUBUN not like", value, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunIn(List<String> values) {
            addCriterion("SALES_PLAN_KUBUN in", values, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunNotIn(List<String> values) {
            addCriterion("SALES_PLAN_KUBUN not in", values, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_KUBUN between", value1, value2, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanKubunNotBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_KUBUN not between", value1, value2, "salesPlanKubun");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateIsNull() {
            addCriterion("SALES_PLAN_SALES_EXPECTED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateIsNotNull() {
            addCriterion("SALES_PLAN_SALES_EXPECTED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE =", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE <>", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateGreaterThan(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE >", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE >=", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateLessThan(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE <", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE <=", value, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateIn(List<Date> values) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE in", values, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE not in", values, "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE between", value1, value2,
                    "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanSalesExpectedDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("SALES_PLAN_SALES_EXPECTED_DATE not between", value1, value2,
                    "salesPlanSalesExpectedDate");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleIsNull() {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE is null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleIsNotNull() {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE is not null");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleEqualTo(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE =", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleNotEqualTo(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE <>", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleGreaterThan(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE >", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleGreaterThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE >=", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleLessThan(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE <", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleLessThanOrEqualTo(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE <=", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleLike(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE like", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleNotLike(String value) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE not like", value, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleIn(List<String> values) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE in", values, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleNotIn(List<String> values) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE not in", values, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE between", value1, value2, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andSalesPlanCustomerResponsibleNotBetween(String value1, String value2) {
            addCriterion("SALES_PLAN_CUSTOMER_RESPONSIBLE not between", value1, value2, "salesPlanCustomerResponsible");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("UPDATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("UPDATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("UPDATE_TIME =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("UPDATE_TIME <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("UPDATE_TIME >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("UPDATE_TIME <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("UPDATE_TIME <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("UPDATE_TIME in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("UPDATE_TIME not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("UPDATE_TIME not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("UPDATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("UPDATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("UPDATE_USER =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("UPDATE_USER <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("UPDATE_USER >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("UPDATE_USER <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("UPDATE_USER like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("UPDATE_USER not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("UPDATE_USER in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("UPDATE_USER not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("UPDATE_USER between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated do_not_delete_during_merge Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table
     * SCHEMA01.SALES_ACTIVITY
     *
     * @mbg.generated Sun Apr 21 02:45:40 JST 2019
     */
    public static class Criterion {
        /** Where句. */
        private String condition;

        /** Where句(値). */
        private Object value;

        /** LIKE検索の場合の後方値. */
        private Object secondValue;

        /** 値が設定されているか. */
        private boolean noValue;

        /** 完全一致フラグ. */
        private boolean singleValue;

        /** 前方一致フラグ. */
        private boolean betweenValue;

        /** List保持. */
        private boolean listValue;

        /** タイプハンドラ. */
        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
